name: CI

on:
  push:
    branches:
      - ci-pipeline2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build bongoci from source
        run: go build -o ./bongoci ./cmd/ci
      - name: Build, test and package with bongoci
        run: ./bongoci run TEST BUILD_BONGOCI       
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./out/
