# This workflow builds the bongoci binary then run the TEST and BUILD_BONGOCI tasks from build.bongo.
# Finally, it uploads the generated artifacts.
# Basically, it builds bongoci twice, first using standard go build and then using itself.
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build bongoci from source
        run: go build -o ./bongoci ./cmd/ci
      - name: Build, test and package with bongoci
        run: ./bongoci run --github-actions-cache=true TEST BUILD_BONGOCI       
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./out/
